#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

dry_run="0"

if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "no xdg config hom"
    echo "using ~/.config"
    XDG_CONFIG_HOME=$HOME/.config
fi

if [ -z "$DEV_ENV" ]; then
    echo "env var DEV_ENV needs to be present"
    exit 1
fi

while [[ $# -gt 0 ]]; do
	if [[ $1 == "--dry" ]]; then
		dry_run="1"
	fi
	shift
done

log() {
	if [[ $dry_run == "1" ]]; then
		echo "[DRY_RUN]: $@"
	else
		echo "$@"
	fi
}

log "env: $DEV_ENV"

execute() {
	log "execute $@"
	if [[ $dry_run == "1" ]]; then
		return
	fi
	"$@"
}

copy_dir() {
	from=$1
	to=$2
	
	pushd $from > /dev/null
    (	
        dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
        for dir in $dirs; do
            execute rm -rf $to/$(basename $dir)
            execute cp -r $dir $to/$(basename $dir)
        done
    )
	popd > /dev/null
}

copy_file() {
	from=$1
	to=$2
	name=$(basename $from)

	execute rm $to/$name
	execute cp $from $to/$name
}

copy_dir $DEV_ENV/env/.config $XDG_CONFIG_HOME
copy_dir $DEV_ENV/env/.local $HOME/.local

copy_file $DEV_ENV/env/.zsh_profile $HOME
copy_file $DEV_ENV/env/.zshrc $HOME

copy_file $DEV_ENV/tmux-sessionizer/tmux-sessionizer $HOME/.local/scripts
copy_file $DEV_ENV/env/.tmux-sessionizer $HOME

copy_file $DEV_ENV/dev-env $HOME/.local/scripts

hyprctl reload
