#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

grep=""
dry_run="0"

while [[ $# -gt 0 ]]; do
	if [[ $1 == "--dry" ]]; then
		dry_run="1"
	else
		grep="$1"
	fi
	shift
done

log() {
	if [[ $dry_run == "1" ]]; then
		echo "[DRY_RUN]: $@"
	else
		echo "$@"
	fi
}


execute() {
	log "execute $@"
	if [[ $dry_run == "1" ]]; then
		return
	fi
	"$@"
}

log "RUN: env: $script_dir --grep: $grep"

runs_dir=$(find $script_dir/runs -maxdepth 1 -mindepth 1 -executable -type f)

for script in $runs_dir; do
	if echo "$script" | grep -qv "$grep"; then
		log "filtering $script"
		continue
	fi

	execute $script
done
