#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

grep=""
dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
	if [[ $1 == "--dry" ]]; then
		dry_run="1"
	else
		grep="$1"
	fi
	shift
done

log() {
	if [[ $dry_run == "1" ]]; then
		echo "[DRY_RUN]: $1"
	else
		echo "$1"
	fi
}


execute() {
	log "running script: $@"
	if [[ $dry_run == "1" ]]; then
		return
	fi
	"$@"
}

log "RUN: env: $env -- grep: $grep"

runs_dir=$(find $script_dir/runs -maxdepth 1 -mindepth 1 -executable -type f)

for s in $runs_dir; do
    if basename $s | grep -vq "$grep"; then
        log "grep \"$grep\" filtered out $s"
		continue
	fi

	execute $script
done
